name: nekobot-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - requests
  - matplotlib
  - discord.py 
  - google-generativeai
  - requests
  - python-dotenv
  - google-api-python-client
  - colorama 
  - tenacity
